CREATE TABLE IF NOT EXISTS sensors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(100) NOT NULL,
    sensor_type VARCHAR(100) NOT NULL,
    bus_type VARCHAR(100) NOT NULL,
    bus_address VARCHAR(100) NOT NULL,
    is_available boolean NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS measurements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor BIGINT NOT NULL,
    measured_value DOUBLE PRECISION NOT NULL,
    measured_at TIMESTAMP NOT NULL,
    received_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_measure UNIQUE (sensor, measured_at),
    CONSTRAINT fk_measurements_sensors FOREIGN KEY (sensor) REFERENCES sensors(id) ON DELETE CASCADE
);